### ISSUE TITLE
[BUG]: Error initializing sql store within zenml server

### ISSUE THREAD

**Issue by tanken** [zenml-io/zenml#1132]
### System Information

Deployment on cloud/eks

### What happened?

I deployed a Zenml server running as a pod in my K8 cluster and I plan to switch out the local sqlite with an external mysql db on RDS (v 5.7.40), after overwriting the ZENML_STORE_URL env variable with the RDS hostname in the uri schema mysql://user:password@rds-hostname:3306/database.

I redeployed the deployment/pod and noticed this error
`zenml.zen_stores.sql_zen_store - DEBUG - Initializing SqlZenStore at mysql://xxx.rds.amazonaws.com:3306 (sql_zen_store.py:656)`

### Reproduction steps

1. Added the mysql uri as value for ZENML_STORE_URL env variables
2. Using kubernetes/deployment to spin up zenml server as a pod

### Relevant log output

```shell
2022-12-02 07:52:44,590 - zenml.zen_server.utils - DEBUG - Initializing ZenML Store for FastAPI... (utils.py:68)
2022-12-02 07:52:44,591 - zenml.config.global_config - DEBUG - Writing config to /zenml/.zenconfig/config.yaml (global_config.py:356)
2022-12-02 07:52:44,592 - zenml.config.global_config - INFO - Initializing the ZenML global configuration version to 0.22.0 (global_config.py:291)
2022-12-02 07:52:44,592 - zenml.config.global_config - DEBUG - Writing config to /zenml/.zenconfig/config.yaml (global_config.py:356)
2022-12-02 07:52:44,959 - zenml.config.global_config - DEBUG - Using environment variables to configure the default store (global_config.py:557)
2022-12-02 07:52:44,960 - zenml.zen_stores.base_zen_store - DEBUG - Creating store with config 'type=<StoreType.SQL: 'sql'> url='mysql://xxx:xxx@xxx.rds.amazonaws.com:3306/database' ssl_verify_server_cert='False''... (base_zen_store.py:200)
2022-12-02 07:52:45,015 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInMaterializer'> for <class 'bool'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,015 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInMaterializer'> for <class 'float'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,015 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInMaterializer'> for <class 'int'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,015 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInMaterializer'> for <class 'str'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,015 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BytesMaterializer'> for <class 'bytes'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,016 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInContainerMaterializer'> for <class 'dict'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,016 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInContainerMaterializer'> for <class 'list'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,016 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInContainerMaterializer'> for <class 'set'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,016 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.built_in_materializer.BuiltInContainerMaterializer'> for <class 'tuple'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,200 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.numpy_materializer.NumpyMaterializer'> for <class 'numpy.ndarray'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,458 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.pandas_materializer.PandasMaterializer'> for <class 'pandas.core.frame.DataFrame'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,458 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.pandas_materializer.PandasMaterializer'> for <class 'pandas.core.series.Series'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,518 - zenml.materializers.default_materializer_registry - DEBUG - Registered materializer <class 'zenml.materializers.service_materializer.ServiceMaterializer'> for <class 'zenml.services.service.BaseService'> (default_materializer_registry.py:45)
2022-12-02 07:52:45,536 - zenml.zen_stores.sql_zen_store - DEBUG - Initializing SqlZenStore at mysql://zenml.crdzqpbsbamt.eu-central-1.rds.amazonaws.com:3306 (sql_zen_store.py:656)
ERROR:    Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_stores/base_zen_store.py", line 105, in __init__
    self._initialize()
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_stores/sql_zen_store.py", line 659, in _initialize
    self._metadata_store = MetadataStore(config=metadata_config)
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_stores/metadata_store.py", line 102, in __init__
    self.store = metadata_store.MetadataStore(
  File "/usr/local/lib/python3.8/site-packages/ml_metadata/metadata_store/metadata_store.py", line 103, in __init__
    self._metadata_store = metadata_store_serialized.CreateMetadataStore(
RuntimeError: Creating database database in ConnectImplmysql_query failed: errno: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 621, in lifespan
    async with self.lifespan_context(app):
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 518, in __aenter__
    await self._router.startup()
  File "/usr/local/lib/python3.8/site-packages/starlette/routing.py", line 600, in startup
    handler()
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_server/zen_server_api.py", line 87, in initialize
    initialize_zen_store()
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_server/utils.py", line 69, in initialize_zen_store
    _zen_store = GlobalConfiguration().zen_store
  File "/usr/local/lib/python3.8/site-packages/zenml/config/global_config.py", line 263, in __custom_getattribute__
    value = super().__getattribute__(key)
  File "/usr/local/lib/python3.8/site-packages/zenml/config/global_config.py", line 649, in zen_store
    self.set_default_store()
  File "/usr/local/lib/python3.8/site-packages/zenml/config/global_config.py", line 576, in set_default_store
    self._configure_store(default_store_cfg)
  File "/usr/local/lib/python3.8/site-packages/zenml/config/global_config.py", line 385, in _configure_store
    store = BaseZenStore.create_store(
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_stores/base_zen_store.py", line 202, in create_store
    store = store_class(
  File "/usr/local/lib/python3.8/site-packages/zenml/zen_stores/base_zen_store.py", line 107, in __init__
    raise RuntimeError(
RuntimeError: Error initializing sql store with URL 'mysql://xxx.rds.amazonaws.com:3306': Creating database database in ConnectImplmysql_query failed: errno: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1, error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'database' at line 1
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@tanken thanks for creating this issue. Which ZenML version are you using?  It seems that this error lies in the metadata store creation from `ml-pipelines-sdk` and today we will make a rc release that gets rid of that dependency. So perhaps wait a few hours and try to rc version to see if that fixes it?

In the meanwhile, we can investigate if you tell us your ZenML version. I would also suggest you drop all databases that you have currently in the RDS

**Comment by tanken** [comment]
@htahir1 thanks for a prompt reply. I'm using the latest image from https://hub.docker.com/r/zenmldocker/zenml-server to build my deployment/pod, if that helps. The server is working fine when it uses sqlite, and I have not made any connection from zenml client.

**Comment by htahir1** [comment]
@tanken The 0.30.0rc0 (without the dependency) and 0.23.0 (the new latest stable release) are both out now . Would you mind trying again with the rc?

**Comment by tanken** [comment]
@htahir1 i have tried with 0.30.0rc0 as well as creating the database in rds before starting the pod and it worked.
