### ISSUE TITLE
[BUG]: Server Error when materializing single row Pandas DataFrame

### ISSUE THREAD

**Issue by Christopher-Norman** [zenml-io/zenml#1391]
### Contact Details [Optional]

chris@fuzzylabs.ai

### System Information

ZENML_LOCAL_VERSION: 0.34.0
ZENML_SERVER_VERSION: 0.34.0
ZENML_SERVER_DATABASE: sqlite
ZENML_SERVER_DEPLOYMENT_TYPE: local
ZENML_CONFIG_DIR: /Users/christophernorman/Library/Application Support/zenml
ZENML_LOCAL_STORE_DIR: /Users/christophernorman/Library/Application Support/zenml/local_stores
ZENML_SERVER_URL: REMOVED
ZENML_ACTIVE_REPOSITORY_ROOT: /Users/christophernorman/reproduce-zenml-bug
PYTHON_VERSION: 3.10.9
ENVIRONMENT: native
SYSTEM_INFO: {'os': 'mac', 'mac_version': '10.16'}
ACTIVE_WORKSPACE: default
ACTIVE_STACK: default
ACTIVE_USER: default
TELEMETRY_STATUS: enabled
ANALYTICS_CLIENT_ID: d66ee04d-9e06-4057-b159-89991a575308
ANALYTICS_USER_ID: 8f970f2d-2027-48fe-b98f-cc3be62b23ec
ANALYTICS_SERVER_ID: d66ee04d-9e06-4057-b159-89991a575308
INTEGRATIONS: ['kaniko']
PACKAGES: {'certifi': '2022.12.7', 'pytz': '2022.7.1', 'setuptools': '65.6.3', 'cryptography': '39.0.2', 'pyzmq': '25.0.0', 'pip': '23.0.1', 'packaging': '23.0', 'attrs': '22.2.0', 'argon2-cffi': 
'21.3.0', 'argon2-cffi-bindings': '21.2.0', 'isoduration': '20.11.0', 'rich': '12.6.0', 'websockets': '10.4', 'ipython': '8.11.0', 'click': '8.1.3', 'jupyter-client': '8.0.3', 'ipywidgets': '7.7.3', 
'nbconvert': '7.2.9', 'ipykernel': '6.21.3', 'notebook': '6.5.3', 'tornado': '6.2', 'docker': '6.0.1', 'bleach': '6.0.0', 'psutil': '5.9.4', 'traitlets': '5.9.0', 'nbformat': '5.7.3', 'pyyaml': '5.4.1', 
'jupyter-core': '5.2.0', 'decorator': '5.1.1', 'smmap': '5.0.0', 'jsonschema': '4.17.3', 'beautifulsoup4': '4.11.2', 'rsa': '4.9', 'pexpect': '4.8.0', 'typing-extensions': '4.5.0', 'gitdb': '4.0.10', 
'bcrypt': '4.0.1', 'widgetsnbextension': '3.6.2', 'anyio': '3.6.2', 'asgiref': '3.6.0', 'idna': '3.4', 'python-jose': '3.3.0', 'gitpython': '3.1.31', 'jinja2': '3.1.2', 'platformdirs': '3.1.0', 
'charset-normalizer': '3.1.0', 'prompt-toolkit': '3.0.38', 'requests': '2.28.2', 'pycparser': '2.21', 'fastjsonschema': '2.16.3', 'pygments': '2.14.0', 'python-dateutil': '2.8.2', 'pyparsing': '2.4.7', 
'jupyter-server': '2.4.0', 'soupsieve': '2.4', 'jsonpointer': '2.3', 'asttokens': '2.2.1', 'markupsafe': '2.1.2', 'python-json-logger': '2.0.7', 'mistune': '2.0.5', 'greenlet': '2.0.2', 'urllib3': 
'1.26.14', 'numpy': '1.24.2', 'six': '1.16.0', 'cffi': '1.15.1', 'webcolors': '1.12', 'pydantic': '1.10.5', 'backoff': '1.10.0', 'alembic': '1.8.1', 'send2trash': '1.8.0', 'distro': '1.8.0', 'passlib': 
'1.7.4', 'debugpy': '1.6.6', 'monotonic': '1.6', 'nest-asyncio': '1.5.6', 'pandas': '1.5.3', 'fqdn': '1.5.1', 'websocket-client': '1.5.1', 'pandocfilters': '1.5.0', 'sqlalchemy': '1.4.41', 
'analytics-python': '1.4.0', 'sniffio': '1.3.0', 'mako': '1.2.4', 'arrow': '1.2.3', 'tinycss2': '1.2.1', 'executing': '1.2.0', 'uri-template': '1.2.0', 'jupyterlab-widgets': '1.1.2', 'pymysql': '1.0.2', 
'python-dotenv': '1.0.0', 'fastapi': '0.75.2', 'wheel': '0.38.4', 'sqlalchemy-utils': '0.38.3', 'zenml': '0.34.0', 'pyrsistent': '0.19.3', 'httplib2': '0.19.1', 'validators': '0.18.2', 'jedi': '0.18.2', 
'ecdsa': '0.18.0', 'uvicorn': '0.17.6', 'terminado': '0.17.1', 'starlette': '0.17.1', 'uvloop': '0.17.0', 'prometheus-client': '0.16.0', 'h11': '0.14.0', 'python-terraform': '0.10.1', 'commonmark': 
'0.9.1', 'parso': '0.8.3', 'watchgod': '0.8.2', 'pickleshare': '0.7.5', 'nbclient': '0.7.2', 'defusedxml': '0.7.1', 'ptyprocess': '0.7.0', 'jupyter-events': '0.6.3', 'stack-data': '0.6.2', 'nbclassic': 
'0.5.3', 'webencodings': '0.5.1', 'httptools': '0.5.0', 'pyasn1': '0.4.8', 'jupyter-server-terminals': '0.4.4', 'click-params': '0.3.0', 'wcwidth': '0.2.6', 'pure-eval': '0.2.2', 'jupyterlab-pygments': 
'0.2.2', 'notebook-shim': '0.2.2', 'fastapi-utils': '0.2.1', 'backcall': '0.2.0', 'ipython-genutils': '0.2.0', 'matplotlib-inline': '0.1.6', 'rfc3339-validator': '0.1.4', 'appnope': '0.1.3', 'comm': 
'0.1.2', 'rfc3986-validator': '0.1.1', 'sqlmodel': '0.0.8', 'python-multipart': '0.0.6', 'sqlalchemy2-stubs': '0.0.2a32'}

### What happened?

When a step returns a Pandas DataFrame with one row where at least one of the columns is a numeric value, an `Internal Server Error` is thrown. 

In the case of having a single row, it seems this is due to how Pandas calculates the (population) standard deviation in the metadata. When there is only one row the standard deviation calculation divides by `n-1` which, in this case, equals `0` and therefore, `standard deviation = NaN`. When this is being materialized the ZenML server logs show `ValueError: Out of range float values are not JSON compliant` which is likely due to encoding the `NaN` float value. 

What was expected to happen?
Ideally, DataFrames with a single row should still be able to be materialized. 

### Reproduction steps

Run the pipeline example below using the default local stack.

Reproducible example code below:
```
from zenml.steps import step
from zenml.pipelines import pipeline
import pandas as pd


@step
def create_pandas_df() -> pd.DataFrame:
    data = {
    "col1": ['row1'],
    "col2": [1]
    }

    df = pd.DataFrame(data)
    return df

@step
def print_dataframe(df: pd.DataFrame) -> None:
    print(df)

@pipeline
def example_pipeline(create_pandas_df, print_dataframe):
    df = create_pandas_df()
    
    print_dataframe(df)


if __name__ == "__main__":
    pipe = example_pipeline(create_pandas_df(), print_dataframe())
    pipe.run()
```

### Relevant log output

```shell
PIPELINE RUN OUTPUT:

Failed to run step create_pandas_df.
Pipeline run example_pipeline-2023_03_07-15_08_54_643354 failed.
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/christophernorman/KO/reproduce-zenml-bug/main.py:32 in <module>                           │
│                                                                                                  │
│   29                                                                                             │
│   30 if __name__ == "__main__":                                                                  │
│   31 │   pipe = example_pipeline(create_pandas_df(), print_dataframe())                          │
│ ❱ 32 │   pipe.run()                                                                              │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/pipelines/base_pipeline.py:53 │
│ 2 in run                                                                                         │
│                                                                                                  │
│    529 │   │   │   # unexpected behavior                                                         │
│    530 │   │   │   constants.SHOULD_PREVENT_PIPELINE_EXECUTION = True                            │
│    531 │   │   │   try:                                                                          │
│ ❱  532 │   │   │   │   stack.deploy_pipeline(                                                    │
│    533 │   │   │   │   │   deployment=deployment_model,                                          │
│    534 │   │   │   │   )                                                                         │
│    535 │   │   │   finally:                                                                      │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/stack/stack.py:843 in         │
│ deploy_pipeline                                                                                  │
│                                                                                                  │
│    840 │   │   Returns:                                                                          │
│    841 │   │   │   The return value of the call to `orchestrator.run_pipeline(...)`.             │
│    842 │   │   """                                                                               │
│ ❱  843 │   │   return self.orchestrator.run(deployment=deployment, stack=self)                   │
│    844 │                                                                                         │
│    845 │   def _validate_build(                                                                  │
│    846 │   │   self,                                                                             │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/base_orchestrat │
│ or.py:160 in run                                                                                 │
│                                                                                                  │
│   157 │   │   """                                                                                │
│   158 │   │   self._prepare_run(deployment=deployment)                                           │
│   159 │   │   try:                                                                               │
│ ❱ 160 │   │   │   result = self.prepare_or_run_pipeline(                                         │
│   161 │   │   │   │   deployment=deployment, stack=stack                                         │
│   162 │   │   │   )                                                                              │
│   163 │   │   finally:                                                                           │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/local/local_orc │
│ hestrator.py:79 in prepare_or_run_pipeline                                                       │
│                                                                                                  │
│    76 │   │   │   │   │   step.config.name,                                                      │
│    77 │   │   │   │   )                                                                          │
│    78 │   │   │                                                                                  │
│ ❱  79 │   │   │   self.run_step(                                                                 │
│    80 │   │   │   │   step=step,                                                                 │
│    81 │   │   │   )                                                                              │
│    82                                                                                            │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/base_orchestrat │
│ or.py:180 in run_step                                                                            │
│                                                                                                  │
│   177 │   │   │   step=step,                                                                     │
│   178 │   │   │   orchestrator_run_id=self.get_orchestrator_run_id(),                            │
│   179 │   │   )                                                                                  │
│ ❱ 180 │   │   launcher.launch()                                                                  │
│   181 │                                                                                          │
│   182 │   @staticmethod                                                                          │
│   183 │   def requires_resources_in_orchestration_environment(                                   │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.p │
│ y:198 in launch                                                                                  │
│                                                                                                  │
│   195 │   │   │                                                                                  │
│   196 │   │   │   if execution_needed:                                                           │
│   197 │   │   │   │   try:                                                                       │
│ ❱ 198 │   │   │   │   │   self._run_step(                                                        │
│   199 │   │   │   │   │   │   pipeline_run=pipeline_run,                                         │
│   200 │   │   │   │   │   │   step_run=step_run_response,                                        │
│   201 │   │   │   │   │   )                                                                      │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.p │
│ y:379 in _run_step                                                                               │
│                                                                                                  │
│   376 │   │   │   │   │   step_run_info=step_run_info,                                           │
│   377 │   │   │   │   )                                                                          │
│   378 │   │   │   else:                                                                          │
│ ❱ 379 │   │   │   │   self._run_step_without_step_operator(                                      │
│   380 │   │   │   │   │   step_run_info=step_run_info,                                           │
│   381 │   │   │   │   │   input_artifacts=step_run.input_artifacts,                              │
│   382 │   │   │   │   │   output_artifact_uris=output_artifact_uris,                             │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/step_launcher.p │
│ y:447 in _run_step_without_step_operator                                                         │
│                                                                                                  │
│   444 │   │   │   output_artifact_uris: The output artifact URIs of the current step.            │
│   445 │   │   """                                                                                │
│   446 │   │   runner = StepRunner(step=self._step, stack=self._stack)                            │
│ ❱ 447 │   │   runner.run(                                                                        │
│   448 │   │   │   input_artifacts=input_artifacts,                                               │
│   449 │   │   │   output_artifact_uris=output_artifact_uris,                                     │
│   450 │   │   │   step_run_info=step_run_info,                                                   │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/step_runner.py: │
│ 152 in run                                                                                       │
│                                                                                                  │
│   149 │   │   output_artifact_ids = publish_output_artifacts(                                    │
│   150 │   │   │   output_artifacts=output_artifacts,                                             │
│   151 │   │   )                                                                                  │
│ ❱ 152 │   │   publish_output_artifact_metadata(                                                  │
│   153 │   │   │   output_artifact_ids=output_artifact_ids,                                       │
│   154 │   │   │   output_artifact_metadata=artifact_metadata,                                    │
│   155 │   │   )                                                                                  │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/orchestrators/publish_utils.p │
│ y:70 in publish_output_artifact_metadata                                                         │
│                                                                                                  │
│    67 │   client = Client()                                                                      │
│    68 │   for output_name, artifact_metadata in output_artifact_metadata.items():                │
│    69 │   │   artifact_id = output_artifact_ids[output_name]                                     │
│ ❱  70 │   │   client.create_run_metadata(                                                        │
│    71 │   │   │   metadata=artifact_metadata, artifact_id=artifact_id                            │
│    72 │   │   )                                                                                  │
│    73                                                                                            │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/client.py:3306 in             │
│ create_run_metadata                                                                              │
│                                                                                                  │
│   3303 │   │   │   │   value=value,                                                              │
│   3304 │   │   │   │   type=metadata_type,                                                       │
│   3305 │   │   │   )                                                                             │
│ ❱ 3306 │   │   │   metadata_model = self.zen_store.create_run_metadata(run_metadata)             │
│   3307 │   │   │   created_metadata[key] = metadata_model                                        │
│   3308 │   │   return created_metadata                                                           │
│   3309                                                                                           │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 1770 in create_run_metadata                                                                      │
│                                                                                                  │
│   1767 │   │   Returns:                                                                          │
│   1768 │   │   │   The created run metadata.                                                     │
│   1769 │   │   """                                                                               │
│ ❱ 1770 │   │   return self._create_workspace_scoped_resource(                                    │
│   1771 │   │   │   resource=run_metadata,                                                        │
│   1772 │   │   │   response_model=RunMetadataResponseModel,                                      │
│   1773 │   │   │   route=RUN_METADATA,                                                           │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 2156 in _create_workspace_scoped_resource                                                        │
│                                                                                                  │
│   2153 │   │   Returns:                                                                          │
│   2154 │   │   │   The created resource.                                                         │
│   2155 │   │   """                                                                               │
│ ❱ 2156 │   │   return self._create_resource(                                                     │
│   2157 │   │   │   resource=resource,                                                            │
│   2158 │   │   │   response_model=response_model,                                                │
│   2159 │   │   │   route=f"{WORKSPACES}/{str(resource.workspace)}{route}",                       │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 2134 in _create_resource                                                                         │
│                                                                                                  │
│   2131 │   │   Returns:                                                                          │
│   2132 │   │   │   The created resource.                                                         │
│   2133 │   │   """                                                                               │
│ ❱ 2134 │   │   response_body = self.post(f"{route}", body=resource, params=params)               │
│   2135 │   │   return response_model.parse_obj(response_body)                                    │
│   2136 │                                                                                         │
│   2137 │   def _create_workspace_scoped_resource(                                                │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 2080 in post                                                                                     │
│                                                                                                  │
│   2077 │   │   │   The response body.                                                            │
│   2078 │   │   """                                                                               │
│   2079 │   │   logger.debug(f"Sending POST request to {path}...")                                │
│ ❱ 2080 │   │   return self._request(                                                             │
│   2081 │   │   │   "POST",                                                                       │
│   2082 │   │   │   self.url + API + VERSION_1 + path,                                            │
│   2083 │   │   │   data=body.json(),                                                             │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 1997 in _request                                                                                 │
│                                                                                                  │
│   1994 │   │   """                                                                               │
│   1995 │   │   params = {k: str(v) for k, v in params.items()} if params else {}                 │
│   1996 │   │   try:                                                                              │
│ ❱ 1997 │   │   │   return self._handle_response(                                                 │
│   1998 │   │   │   │   self.session.request(                                                     │
│   1999 │   │   │   │   │   method,                                                               │
│   2000 │   │   │   │   │   url,                                                                  │
│                                                                                                  │
│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 1970 in _handle_response                                                                         │
│                                                                                                  │
│   1967 │   │   │   │   response_msg = response.text                                              │
│   1968 │   │   │   raise RuntimeError(response_msg)                                              │
│   1969 │   │   elif response.status_code == 500:                                                 │
│ ❱ 1970 │   │   │   raise RuntimeError(response.text)                                             │
│   1971 │   │   else:                                                                             │
│   1972 │   │   │   raise RuntimeError(                                                           │
│   1973 │   │   │   │   "Error retrieving from API. Got response "                                │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Internal Server Error


PIPELINE RUN OUTPUT WITH DEBUG:

│ /opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/zenml/zen_stores/rest_zen_store.py: │
│ 2080 in post                                                                                     │
│                                                                                                  │
│   2077 │   │   │   The response body.                                                            │
│   2078 │   │   """                                                                               │
│   2079 │   │   logger.debug(f"Sending POST request to {path}...")                                │
│ ❱ 2080 │   │   return self._request(                                                             │
│   2081 │   │   │   "POST",                                                                       │
│   2082 │   │   │   self.url + API + VERSION_1 + path,                                            │
│   2083 │   │   │   data=body.json(),                                                             │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │   body = RunMetadataRequestModel(                                                            │ │
│ │          │   user=UUID('8f970f2d-2027-48fe-b98f-cc3be62b23ec'),                              │ │
│ │          │   workspace=UUID('d3af1b3e-f4a3-4a76-8255-65244433a7a2'),                         │ │
│ │          │   pipeline_run_id=None,                                                           │ │
│ │          │   step_run_id=None,                                                               │ │
│ │          │   artifact_id=UUID('dc672f5f-054d-4d73-9fe7-693e986b1472'),                       │ │
│ │          │   stack_component_id=None,                                                        │ │
│ │          │   key='std',                                                                      │ │
│ │          │   value={'col2': nan},                                                            │ │
│ │          │   type='dict'                                                                     │ │
│ │          )                                                                                   │ │
│ │ kwargs = {}                                                                                  │ │
│ │ params = None                                                                                │ │
│ │   path = '/workspaces/d3af1b3e-f4a3-4a76-8255-65244433a7a2/run-metadata'                     │ │
│ │   self = RestZenStore(                                                                       │ │
│ │          │   config=RestZenStoreConfiguration(                                               │ │
│ │          │   │   type=<StoreType.REST: 'rest'>,                                              │ │
│ │          │   │   url='http://127.0.0.1:8237',                                                │ │
│ │          │   │   secrets_store=RestSecretsStoreConfiguration(                                │ │
│ │          │   │   │   type=<SecretsStoreType.REST: 'rest'>                                    │ │
│ │          │   │   ),                                                                          │ │
│ │          │   │   username='default',                                                         │ │
│ │          │   │   password='',                                                                │ │
│ │          │   │                                                                               │ │
│ │          api_token='eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI4Zjk3MGYyZC0yMDI3LTQ4Zm… │ │
│ │          │   │   verify_ssl=True,                                                            │ │
│ │          │   │   http_timeout=30                                                             │ │
│ │          │   ),                                                                              │ │
│ │          │   track_analytics=True                                                            │ │
│ │          )                                                                                   │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │

ZENML LOGS OUTPUT:

INFO:     127.0.0.1:53799 - "POST /api/v1/workspaces/d3af1b3e-f4a3-4a76-8255-65244433a7a2/run-metadata HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/middleware/cors.py", line 84, in __call__
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/fastapi/routing.py", line 251, in app
    response = actual_response_class(response_data, **response_args)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/responses.py", line 49, in __init__
    self.body = self.render(content)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/site-packages/starlette/responses.py", line 174, in render
    return json.dumps(
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/opt/miniconda3/envs/zenml_venv/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
ValueError: Out of range float values are not JSON compliant
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fa9r** [comment]
@Christopher-Norman thanks so much for submitting this, your example allowed me to finally reproduce this. I believe #1395 should fix this. Will let you know once the fix goes live.

**Comment by Christopher-Norman** [comment]
@fa9r Great, thank you.
