### ISSUE TITLE
[FEATURE]: Allow passing arguments to first @step function in ZenML pipeline

### ISSUE THREAD

**Issue by deepakiim** [zenml-io/zenml#494]
### Describe the feature you'd like

ZenML doesnt allow passing arguments to first @step function in ZenML pipeline.
`Only outputs from previous steps can be used as arguments when connecting steps.`

ZenML version 0.6.2
```
import numpy as np
from sklearn.base import ClassifierMixin
from typing import List, Dict

from zenml.integrations.sklearn.helpers.digits import (
    get_digits,
)
from sklearn.base import ClassifierMixin
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from zenml.pipelines import pipeline
from zenml.steps import Output, step

"""## Define ZenML Steps

In the code that follows, you can see that we are defining the various steps of our pipeline. Each step is decorated with `@step`, the main abstraction that is currently available for creating pipeline steps.

The first step is an `import` step that downloads the MNIST dataset and returns four numpy arrays as its output.
"""

@step
def importer(test: List) -> Output(
    X_train=np.ndarray, X_test=np.ndarray, y_train=np.ndarray, y_test=np.ndarray
):
    """Loads the digits array as normal numpy arrays."""
    test
    X_train, X_test, y_train, y_test = get_digits()
    return X_train, X_test, y_train, y_test

"""We then add a `Trainer` step, that takes the imported data and trains a sklearn classifier on the data. Note that the model is not explicitly saved within the step. Under the hood ZenML uses Materializers to automatically persist the Artifacts that result from each step into the Artifact Store."""

@step
def decision_tree_trainer(
    X_train: np.ndarray,
    y_train: np.ndarray,
) -> ClassifierMixin:
    """Train another simple sklearn classifier for the digits dataset."""
    model = DecisionTreeClassifier()
    model.fit(X_train, y_train)
    return model

"""Finally, we add an `Evaluator` step that takes as input the test set and the trained model and evaluates some final metrics."""

@step
def evaluator(
    X_test: np.ndarray,
    y_test: np.ndarray,
    model: ClassifierMixin,
) -> float:
    """Calculate the accuracy on the test set"""
    test_acc = model.score(X_test, y_test)
    print(f"Test accuracy: {test_acc}")
    return test_acc

"""## Define ZenML Pipeline

A pipeline is defined with the `@pipeline` decorator. This defines the various steps of the pipeline and specifies the dependencies between the steps, thereby determining the order in which they will be run.
"""

@pipeline
def mnist_pipeline(
    importer,
    trainer,
    evaluator,
):
    """Links all the steps together in a pipeline"""
    X_train, X_test, y_train, y_test = importer(test=[])
    model = trainer(X_train=X_train, y_train=y_train)
    evaluator(X_test=X_test, y_test=y_test, model=model)

"""## Run the pipeline

Running the pipeline is as simple as calling the `run()` method on an instance of the defined pipeline. Here we explicitly name our pipeline run to make it easier to access later on. Be aware that you can only run the pipeline once with this name. To rerun, rename the the run, or remove the run name.
"""

RUN_NAME_1 = "decision_tree_mnist_training_run"

# Initialize the pipeline
first_pipeline = mnist_pipeline(
    importer=importer(),
    trainer=decision_tree_trainer(),
    evaluator=evaluator(),
)
first_pipeline.run(run_name=RUN_NAME_1) # Make sure to change the name if you want to rerun
```

**OUTPUT LOG**

```
Connected to pydev debugger (build 202.8194.22)
Creating run for pipeline: `mnist_pipeline`
Cache enabled for pipeline `mnist_pipeline`
Using stack `local_stack` to run pipeline `mnist_pipeline`...
Traceback (most recent call last):
  File "/snap/pycharm-professional/225/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/225/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/deepak/projects/mira/mira-ner/property/tsi/model/crf/zenml_quickstart.py", line 135, in <module>
    first_pipeline.run(run_name=RUN_NAME_1) # Make sure to change the name if you want to rerun
  File "/home/deepak/anaconda3/envs/mira-ner/lib/python3.6/site-packages/zenml/pipelines/base_pipeline.py", line 347, in run
    self, runtime_configuration=runtime_configuration
  File "/home/deepak/anaconda3/envs/mira-ner/lib/python3.6/site-packages/zenml/stack/stack.py", line 325, in deploy_pipeline
    pipeline, stack=self, runtime_configuration=runtime_configuration
  File "/home/deepak/anaconda3/envs/mira-ner/lib/python3.6/site-packages/zenml/orchestrators/local/local_orchestrator.py", line 78, in run_pipeline
    tfx_pipeline: TfxPipeline = create_tfx_pipeline(pipeline, stack=stack)
  File "/home/deepak/anaconda3/envs/mira-ner/lib/python3.6/site-packages/zenml/orchestrators/utils.py", line 37, in create_tfx_pipeline
    zenml_pipeline.connect(**zenml_pipeline.steps)
  File "/home/deepak/projects/mira/mira-ner/property/tsi/model/crf/zenml_quickstart.py", line 118, in mnist_pipeline
    X_train, X_test, y_train, y_test = importer(test=[])
  File "/home/deepak/anaconda3/envs/mira-ner/lib/python3.6/site-packages/zenml/steps/base_step.py", line 572, in __call__
    *artifacts, **kw_artifacts
  File "/home/deepak/anaconda3/envs/mira-ner/lib/python3.6/site-packages/zenml/steps/base_step.py", line 527, in _prepare_input_artifacts
    f"Wrong argument type (`{type(artifact)}`) for argument "
zenml.exceptions.StepInterfaceError: Wrong argument type (`<class 'list'>`) for argument 'test' of step 'importer'. Only outputs from previous steps can be used as arguments when connecting steps.
```

### Is your feature request related to a problem?

1. Cannot we reuse the steps in ZenML pipeline for prediction/serving since it doesnt allow taking input record to make on prediction as input to the pipeline.

2. Is there an example in Zenml repo where the training pipeline in this official example is reused for serving/prediction? To avoid code duplication and errors?

### How do you solve your current problem with the current status-quo of ZenML?

No

**Comment by htahir1** [comment]
@deepakiim Thanks for the feature request:

It's actually easy to pass in `test` as a list via a `BaseStepConfig` (https://docs.zenml.io/features/pipeline-configuration) 👍 

```python
from zenml.steps import BaseStepConfig

class ImporterConfig(BaseStepConfig):
    test: List = []

@step
def importer(importer_config: ImporterConfig) -> Output(
    X_train=np.ndarray, X_test=np.ndarray, y_train=np.ndarray, y_test=np.ndarray
):
    """Loads the digits array as normal numpy arrays."""
    test
    X_train, X_test, y_train, y_test = get_digits()
    return X_train, X_test, y_train, y_test

...

# Initialize the pipeline
first_pipeline = mnist_pipeline(
    importer=importer(importer_config=ImporterConfig(test=[])),  # you can send it here or via a yaml file
    trainer=decision_tree_trainer(),
    evaluator=evaluator(),
)
first_pipeline.run(run_name=RUN_NAME_1) # Make sure to change the name if you want to rerun
```

The above paradigm can be used to parameterize the pipeline (see docs above). 

In order see an example of a training/prediction pipeline you can look at the [NBA ZenFile](https://github.com/zenml-io/zenfiles/blob/main/nba-pipeline/Building%20and%20Using%20An%20MLOPs%20Stack%20With%20ZenML.ipynb)

**Comment by htahir1** [comment]
You're right @deepakiim. Currently, ZenML is designed for batch use-cases and streaming use-cases are something we are not supporting with any extra features (bear in mind ZenML is just a framework so you can of course create custom logic in your steps that leverage streaming ingestion)

>  Why not allow importer to accept an argument say importer(input_text) directly instead of making it a config and the pass?

Having said that you can of course change the `ImporterConfig` to this.

```python
class ImporterConfig(BaseStepConfig):
    input_text: str
```

To make it accept an input_text as a parameter.

You can also design your step as an API like we did in the [functional guide](https://github.com/zenml-io/zenml/blob/main/examples/functional_api/chapter_6.py) 

```python
class ImporterConfig(BaseStepConfig):
    n_days: int = 1


def get_X_y_from_api(n_days: int = 1, is_train: bool = True):
    url = (
        "https://storage.googleapis.com/zenml-public-bucket/mnist"
        "/mnist_handwritten_train.json"
        if is_train
        else "https://storage.googleapis.com/zenml-public-bucket/mnist"
        "/mnist_handwritten_test.json"
    )
    df = pd.DataFrame(requests.get(url).json())
    X = df["image"].map(lambda x: np.array(x)).values
    X = np.array([x.reshape(28, 28) for x in X])
    y = df["label"].map(lambda y: np.array(y)).values
    return X, y


@step
def dynamic_importer(
    config: ImporterConfig,
) -> Output(
    X_train=np.ndarray, y_train=np.ndarray, X_test=np.ndarray, y_test=np.ndarray
):
    """Downloads the latest data from a mock API."""
    X_train, y_train = get_X_y_from_api(n_days=config.n_days, is_train=True)
    X_test, y_test = get_X_y_from_api(n_days=config.n_days, is_train=False)
    return X_train, y_train, X_test, y_test
```

Does that serve your use-case?

**Comment by deepakiim** [comment]
Feel free to go ahead and close this issue.
