### ISSUE TITLE
[BUG]: Functions with @step decorator throwing TypeError: issubclass() arg 1 must be a class

### ISSUE THREAD

**Issue by deepakiim** [zenml-io/zenml#519]
### What happened?

ZenML version 0.6.2

```
import numpy as np
from sklearn.base import ClassifierMixin
from typing import List, Dict

from zenml.integrations.sklearn.helpers.digits import (
    get_digits,
)
from sklearn.base import ClassifierMixin
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from zenml.pipelines import pipeline
from zenml.steps import Output, step

"""## Define ZenML Steps

In the code that follows, you can see that we are defining the various steps of our pipeline. Each step is decorated with `@step`, the main abstraction that is currently available for creating pipeline steps.

The first step is an `import` step that downloads the MNIST dataset and returns four numpy arrays as its output.
"""

@step
def importer(test: List) -> Output(
    X_train=np.ndarray, X_test=np.ndarray, y_train=np.ndarray, y_test=np.ndarray
):
    """Loads the digits array as normal numpy arrays."""
    test
    X_train, X_test, y_train, y_test = get_digits()
    return X_train, X_test, y_train, y_test

"""We then add a `Trainer` step, that takes the imported data and trains a sklearn classifier on the data. Note that the model is not explicitly saved within the step. Under the hood ZenML uses Materializers to automatically persist the Artifacts that result from each step into the Artifact Store."""

@step
def decision_tree_trainer(
    X_train: np.ndarray,
    y_train: np.ndarray,
) -> ClassifierMixin:
    """Train another simple sklearn classifier for the digits dataset."""
    model = DecisionTreeClassifier()
    model.fit(X_train, y_train)
    return model

"""Finally, we add an `Evaluator` step that takes as input the test set and the trained model and evaluates some final metrics."""

@step
def evaluator(
    X_test: np.ndarray,
    y_test: np.ndarray,
    model: ClassifierMixin,
) -> float:
    """Calculate the accuracy on the test set"""
    test_acc = model.score(X_test, y_test)
    print(f"Test accuracy: {test_acc}")
    return test_acc

"""## Define ZenML Pipeline

A pipeline is defined with the `@pipeline` decorator. This defines the various steps of the pipeline and specifies the dependencies between the steps, thereby determining the order in which they will be run.
"""

@pipeline
def mnist_pipeline(
    importer,
    trainer,
    evaluator,
):
    """Links all the steps together in a pipeline"""
    X_train, X_test, y_train, y_test = importer(test=[])
    model = trainer(X_train=X_train, y_train=y_train)
    evaluator(X_test=X_test, y_test=y_test, model=model)

"""## Run the pipeline

Running the pipeline is as simple as calling the `run()` method on an instance of the defined pipeline. Here we explicitly name our pipeline run to make it easier to access later on. Be aware that you can only run the pipeline once with this name. To rerun, rename the the run, or remove the run name.
"""

RUN_NAME_1 = "decision_tree_mnist_training_run"

# Initialize the pipeline
first_pipeline = mnist_pipeline(
    importer=importer(),
    trainer=decision_tree_trainer(),
    evaluator=evaluator(),
)
first_pipeline.run(run_name=RUN_NAME_1) # Make sure to change the name if you want to rerun
```
This same code had run earlier in python 3.6 zenml 0.6.2

### Reproduction steps

1.
2.
3.
...

### ZenML Version

0.6.2

### Python Version

3.8

### OS Type

Ubuntu (or other Linux Flavor)

### Relevant log output

```shell
/home/deepak/anaconda3/envs/mira-models/bin/python /snap/pycharm-professional/225/plugins/python/helpers/pydev/pydevd.py --multiproc --qt-support=auto --client 127.0.0.1 --port 38099 --file /home/deepak/.config/JetBrains/PyCharm2020.2/scratches/scratch_18.py
pydev debugger: process 17874 is connecting

Connected to pydev debugger (build 202.8194.22)
Traceback (most recent call last):
  File "/snap/pycharm-professional/225/plugins/python/helpers/pydev/pydevd.py", line 1448, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/snap/pycharm-professional/225/plugins/python/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/home/deepak/.config/JetBrains/PyCharm2020.2/scratches/scratch_18.py", line 22, in <module>
    def importer(test: List) -> Output(
  File "/home/deepak/anaconda3/envs/mira-models/lib/python3.8/site-packages/zenml/steps/step_decorator.py", line 116, in step
    return inner_decorator(_func)
  File "/home/deepak/anaconda3/envs/mira-models/lib/python3.8/site-packages/zenml/steps/step_decorator.py", line 99, in inner_decorator
    return type(  # noqa
  File "/home/deepak/anaconda3/envs/mira-models/lib/python3.8/site-packages/zenml/steps/base_step.py", line 127, in __new__
    if issubclass(arg_type, BaseStepConfig):
  File "/home/deepak/anaconda3/envs/mira-models/lib/python3.8/abc.py", line 102, in __subclasscheck__
    return _abc_subclasscheck(cls, subclass)
TypeError: issubclass() arg 1 must be a class
python-BaseException
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by htahir1** [comment]
@deepakiim This is not a bug (although the error message could be better, we'll add that to the backlog)

You are trying to pass in a list in the importer step `def importer(test: List)` which is not the right way of passing parameters. You should instead do this:

```python
from zenml.steps import BaseStepConfig

class ImporterConfig(BaseStepConfig):
    test: List = []

def importer(config: ImporterConfig):
    config.test  # now available
```

Then the rest of the code is simple:

```python
@pipeline
def mnist_pipeline(
    importer,
    trainer,
    evaluator,
):
    """Links all the steps together in a pipeline"""
    X_train, X_test, y_train, y_test = importer()  # Note first step cannot take anything here!
    model = trainer(X_train=X_train, y_train=y_train)
    evaluator(X_test=X_test, y_test=y_test, model=model)


And the run is where you can send over the list, either via YAML or in code:

```python
RUN_NAME_1 = "decision_tree_mnist_training_run"

# Initialize the pipeline
first_pipeline = mnist_pipeline(
    importer=importer(ImporterConfig(test=[1,2,3])),  # here you send the list in
    trainer=decision_tree_trainer(),
    evaluator=evaluator(),
)
first_pipeline.run(run_name=RUN_NAME_1) # Make sure to change the name if you want to rerun
```

**Comment by deepakiim** [comment]
Ok. Understood.

**Comment by fa9r** [comment]
@deepakiim Thanks again for opening this issue, we have improved the error message, now it should hopefully be more clear what is happening.
