### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by huiwenhan** [zenml-io/zenml#98]
**Describe the bug**
zenml installation error.
**To Reproduce**
`pip install zenml`

**Expected behavior**

**Screenshots**

**Stack Trace**
```
ERROR: Cannot install zenml==0.1.0 and zenml==0.1.1 because these package versions have conflicting dependencies.

The conflict is caused by:
    zenml 0.1.1 depends on tfx==0.25.0
    zenml 0.1.0 depends on tfx==0.25.0

```
** Context (please complete the following information):**
 - OS: [e.g. windows 10]
 - Python Version: [3.9.5]
 - ZenML Version: latest

**Additional information**

**Comment by htahir1** [comment]
Hi @huiwenhan , this issue is caused currently because we support Python >=3.6 < 3.9 therefore, please try to use a supported Python version between that ramge. 3.9.5 support will hopefully arrive soon

**Comment by strickvl** [comment]
I found that I'm unable to install `zenml` on any version of Python, even within the range of >=3.6 < 3.9. I get the same error message / stack trace as the OP.

**Comment by htahir1** [comment]
Ok we're investigating. Thanks @strickvl  ;-)

**Comment by bcdurak** [comment]
Hey @huiwenhan and @strickvl , we have an issue regarding our dependencies on Python <3.9. We are investigating it at the moment and we will update this thread as it develops.

As a temporary solution, I have tested the installation with two clean versions of Python, 3.6.9 and 3.8.2 respectively, which seems to solve the dependency problem in the installation. Let us know if it works for you as well or if there are any other issues.

**Comment by strickvl** [comment]
@bcdurak I got it installing and `init` working with 3.6.9, but only when using raw `pip install`. 

When I did a `pipenv install zenml`, I got the following error message:

```
Adding zenml to Pipfile's [packages]...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✘ Locking Failed!
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 741, in _main
[ResolutionFailure]:       resolve_packages(pre, clear, verbose, system, write, requirements_dir, packages, dev)
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 709, in resolve_packages
[ResolutionFailure]:       requirements_dir=requirements_dir,
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/resolver.py", line 692, in resolve
[ResolutionFailure]:       req_dir=requirements_dir
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 1405, in resolve_deps
[ResolutionFailure]:       req_dir=req_dir,
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 1110, in actually_resolve_deps
[ResolutionFailure]:       resolver.resolve()
[ResolutionFailure]:   File "/usr/local/Cellar/pipenv/2021.5.29/libexec/lib/python3.9/site-packages/pipenv/utils.py", line 835, in resolve
[ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: Could not find a version that matches tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.2.*!=2.3.*,!=2.3.*,!=2.5.*,<2.5,<3,==2.4.1,>=1.15.2,>=2.6.0 (from zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
Tried: 0.12.1, 1.0.0, 1.1.0, 1.2.0, 1.2.1, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.5.1, 1.6.0, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.10.0, 1.10.1, 1.11.0, 1.12.0, 1.12.2, 1.12.3, 1.13.1, 1.13.2, 1.14.0, 1.15.0, 1.15.2, 1.15.3, 1.15.4, 1.15.5, 2.0.0, 2.0.1, 2.0.2, 2.0.3, 2.0.4, 2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.2.0, 2.2.1, 2.2.2, 2.2.3, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.4.0, 2.4.1, 2.4.2, 2.4.3, 2.5.0, 2.5.1, 2.6.0
Skipped pre-versions: 1.1.0rc0, 1.1.0rc1, 1.1.0rc2, 1.2.0rc0, 1.2.0rc1, 1.2.0rc2, 1.3.0rc0, 1.3.0rc1, 1.3.0rc2, 1.4.0rc0, 1.4.0rc1, 1.5.0rc0, 1.5.0rc1, 1.6.0rc0, 1.6.0rc1, 1.7.0rc0, 1.7.0rc1, 1.8.0rc0, 1.8.0rc1, 1.9.0rc0, 1.9.0rc1, 1.9.0rc2, 1.10.0rc0, 1.10.0rc1, 1.11.0rc0, 1.12.0rc0, 1.12.0rc1, 1.12.0rc2, 1.13.0rc0, 1.13.0rc1, 1.13.0rc2, 1.14.0rc0, 1.14.0rc1, 1.15.0rc0, 1.15.0rc1, 1.15.0rc2, 1.15.0rc3, 2.0.0a0, 2.0.0b0, 2.0.0b1, 2.0.0rc0, 2.0.0rc1, 2.0.0rc2, 2.1.0rc0, 2.1.0rc1, 2.1.0rc2, 2.2.0rc0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.0rc4, 2.3.0rc0, 2.3.0rc1, 2.3.0rc2, 2.4.0rc0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.5.0rc0, 2.5.0rc1, 2.5.0rc2, 2.5.0rc3, 2.6.0rc0, 2.6.0rc1, 2.6.0rc2
There are incompatible versions in the resolved dependencies:
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*!=2.3.*,<3,>=1.15.2 (from tensorflow-model-analysis==0.30.0->tfx==0.30.0->zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.5.*,<3,>=1.15.2 (from tfx==0.30.0->zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<2.5,>=1.15.2 (from tensorflow-transform==0.30.0->tfx==0.30.0->zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.15.2 (from tensorflow-data-validation==0.30.0->tfx==0.30.0->zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
  tensorflow!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,<3,>=1.15.2 (from tfx-bsl==0.30.0->tfx==0.30.0->zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
  tensorflow<3,>=2.6.0 (from tensorflow-serving-api==2.6.0->tfx==0.30.0->zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
  tensorflow==2.4.1 (from zenml==0.3.8->-r /var/folders/49/7x17fsrn4knfk852z31cs_vm0000gn/T/pipenv21um7kftrequirements/pipenv-4_56wm4q-constraints.txt (line 2))
```

I get the same message when using `pipenv install zenml` using Python 3.8.2.

As the error message suggests, I can run it with the `--skip-lock` flag, but that isn't really solving the problem. I guess `pipenv` is stricter or runs some dependency checks earlier than `pip`?

In any case, at least a straightforward `pip install zenml` works on those two versions that you specified. I can at least confirm that.

**Comment by bcdurak** [comment]
Hey @strickvl, I am happy to hear that the straightforward installation is working. 

As for the `pipenv` installation on 3.8.2, we need to investigate the issue a bit further. I will update the thread when we have more insight.

**Comment by alex-zenml** [comment]
I reproduced the issue of the quickstart not working.

Steps taken:

- `pip install zenml`
- `git init`
- `zenml init`
- created a `.py` file into which I put (verbatim copy) the code listed in step 2 of the quickstart
- ran the file

I didn't get the dataset download issue that @bcdurak you said you had. Instead, I got the following error:

```
2021-09-13 16:45:44,361 — zenml.pipelines.base_pipeline — INFO — Pipeline Quickstart created.
2021-09-13 16:45:44,361 — zenml.datasources.base_datasource — INFO — Datasource Pima Indians Diabetes Dataset created.
2021-09-13 16:45:44,378 — zenml.pipelines.training_pipeline — INFO — Datasource Pima Indians Diabetes Dataset has no commits. Creating the first one..
2021-09-13 16:45:44,378 — zenml.pipelines.base_pipeline — INFO — Pipeline 1631544344378 created.
2021-09-13 16:45:44,995 — zenml.datasources.csv_datasource — INFO — Matched 1: ['gs://zenml_quickstart/diabetes.csv']
2021-09-13 16:45:44,995 — zenml.datasources.csv_datasource — INFO — Using header from file: gs://zenml_quickstart/diabetes.csv.
2021-09-13 16:45:45,641 — zenml.datasources.csv_datasource — INFO — Header: ['times_pregnant', 'pgc', 'dbp', 'tst', 'insulin', 'bmi', 'pedigree', 'age', 'has_diabetes'].
2021-09-13 16:45:48,659 — apache_beam.internal.gcp.auth — WARNING — Unable to find default credentials to use: The Application Default Credentials are not available. They are available if running in Google Compute Engine. Otherwise, the environment variable GOOGLE_APPLICATION_CREDENTIALS must be defined pointing to a file defining the credentials. See https://developers.google.com/accounts/docs/application-default-credentials for more information.
Connecting anonymously.
2021-09-13 16:45:49,408 — root — WARNING — Make sure that locally built Python SDK docker image has Python 3.8 interpreter.
Traceback (most recent call last):
  File "pima-test.py", line 45, in <module>
    training_pipeline.run()
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/utils/analytics_utils.py", line 177, in inner_func
    result = func(*args, **kwargs)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/pipelines/base_pipeline.py", line 457, in run
    self.run_config(config)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/pipelines/base_pipeline.py", line 378, in run_config
    self.backend.run(config)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/backends/orchestrator/base/orchestrator_base_backend.py", line 108, in run
    tfx_pipeline = self.get_tfx_pipeline(config)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/backends/orchestrator/base/orchestrator_base_backend.py", line 60, in get_tfx_pipeline
    component_list = zen_pipeline.get_tfx_component_list(config)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/pipelines/training_pipeline.py", line 88, in get_tfx_component_list
    self.datasource_commit_id = self.datasource.commit()
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/datasources/base_datasource.py", line 153, in commit
    data_pipeline.run()
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/utils/analytics_utils.py", line 177, in inner_func
    result = func(*args, **kwargs)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/pipelines/base_pipeline.py", line 457, in run
    self.run_config(config)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/pipelines/base_pipeline.py", line 378, in run_config
    self.backend.run(config)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/backends/orchestrator/base/orchestrator_base_backend.py", line 109, in run
    ZenMLLocalDagRunner().run(tfx_pipeline)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/backends/orchestrator/base/zenml_local_orchestrator.py", line 97, in run
    component_launcher.launch()
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/tfx/orchestration/portable/launcher.py", line 431, in launch
    executor_output = self._run_executor(execution_info)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/tfx/orchestration/portable/launcher.py", line 325, in _run_executor
    executor_output = self._executor_operator.run_executor(execution_info)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 141, in run_executor
    return run_with_executor(execution_info, executor)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/tfx/orchestration/portable/python_executor_operator.py", line 65, in run_with_executor
    result = executor.Do(execution_info.input_dict, output_dict,
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/components/data_gen/executor.py", line 56, in Do
    datasource.process(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/zenml/datasources/csv_datasource.py", line 90, in process
    p | 'ReadFromText' >> beam.io.ReadFromText(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/pipeline.py", line 585, in __exit__
    self.result = self.run()
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/pipeline.py", line 564, in run
    return self.runner.run_pipeline(self, self._options)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/direct/direct_runner.py", line 131, in run_pipeline
    return runner.run_pipeline(pipeline, options)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 195, in run_pipeline
    self._latest_run_result = self.run_via_runner_api(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 206, in run_via_runner_api
    return self.run_stages(stage_context, stages)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 384, in run_stages
    stage_results = self._run_stage(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 646, in _run_stage
    self._run_bundle(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 769, in _run_bundle
    result, splits = bundle_manager.process_bundle(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/fn_runner.py", line 1080, in process_bundle
    result_future = self._worker_handler.control_conn.push(process_bundle_req)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/portability/fn_api_runner/worker_handlers.py", line 378, in push
    response = self.worker.do_instruction(request)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 601, in do_instruction
    return getattr(self, request_type)(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/worker/sdk_worker.py", line 639, in process_bundle
    bundle_processor.process_bundle(instruction_id))
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 996, in process_bundle
    input_op_by_transform_id[element.transform_id].process_encoded(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/runners/worker/bundle_processor.py", line 222, in process_encoded
    self.output(decoded_value)
  File "apache_beam/runners/worker/operations.py", line 351, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 353, in apache_beam.runners.worker.operations.Operation.output
  File "apache_beam/runners/worker/operations.py", line 215, in apache_beam.runners.worker.operations.SingletonConsumerSet.receive
  File "apache_beam/runners/worker/operations.py", line 823, in apache_beam.runners.worker.operations.SdfProcessSizedElements.process
  File "apache_beam/runners/worker/operations.py", line 832, in apache_beam.runners.worker.operations.SdfProcessSizedElements.process
  File "apache_beam/runners/common.py", line 1240, in apache_beam.runners.common.DoFnRunner.process_with_sized_restriction
  File "apache_beam/runners/common.py", line 732, in apache_beam.runners.common.PerWindowInvoker.invoke_process
  File "apache_beam/runners/common.py", line 870, in apache_beam.runners.common.PerWindowInvoker._invoke_process_per_window
  File "apache_beam/runners/common.py", line 1368, in apache_beam.runners.common._OutputProcessor.process_outputs
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/textio.py", line 163, in read_records
    with self.open_file(file_name) as file_to_read:
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/filebasedsource.py", line 172, in open_file
    return FileSystems.open(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/filesystems.py", line 244, in open
    return filesystem.open(path, mime_type, compression_type)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/gcp/gcsfilesystem.py", line 177, in open
    return self._path_open(path, 'rb', mime_type, compression_type)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/gcp/gcsfilesystem.py", line 138, in _path_open
    raw_file = gcsio.GcsIO().open(path, mode, mime_type=mime_type)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/gcp/gcsio.py", line 223, in open
    downloader = GcsDownloader(
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/gcp/gcsio.py", line 585, in __init__
    project_number = self._get_project_number(self._bucket)
  File "/Users/strickvl/.local/share/virtualenvs/pima-EMmKrcqa/lib/python3.8/site-packages/apache_beam/io/gcp/gcsio.py", line 166, in get_project_number
    self.bucket_to_project_number[bucket] = bucket_metadata.projectNumber
AttributeError: 'NoneType' object has no attribute 'projectNumber'
```

I don't fully understand what's going on here, but I can dig into it tomorrow.

**Comment by htahir1** [comment]
So after some research, we figured out that the `apache-beam==2.32.0` version caused the above error @alex-zenml. To fix, please downgrade apache-beam for now like so:

```
pip install apache-beam==2.28.0
```

Hope that fixes the issue! We'll make sure to fix it in the next release for sure.
